steps:
  # Build the backend container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/smart-album-backend', './backend']
    id: 'build-backend'

  # Build the frontend container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/smart-album-frontend', './frontend']
    id: 'build-frontend'

  # Push the backend container to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/smart-album-backend']
    id: 'push-backend'

  # Push the frontend container to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/smart-album-frontend']
    id: 'push-frontend'

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'smart-album-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/smart-album-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--timeout'
      - '300s'
      - '--cpu'
      - '1'
      - '--memory'
      - '512Mi'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8080,GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID,STORAGE_BUCKET_NAME=${_STORAGE_BUCKET_NAME},FACE_SIMILARITY_THRESHOLD=0.6'
    id: 'deploy-backend'

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'smart-album-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/smart-album-frontend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'REACT_APP_API_URL=https://smart-album-backend-${_REGION}.a.run.app/api'
    id: 'deploy-frontend'

images:
  - 'gcr.io/$PROJECT_ID/smart-album-backend'
  - 'gcr.io/$PROJECT_ID/smart-album-frontend'

substitutions:
  _STORAGE_BUCKET_NAME: smart-album-photos
  _REGION: us-central1

options:
  logging: CLOUD_LOGGING_ONLY