version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/service-account.json
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - ./service-account.json:/usr/src/app/service-account.json
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend 